using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using BookDB.Logic.Import;
using Xunit;

namespace BookDB.Logic.Tests.Import;

public class ReaderwareDbExportServiceTests : IDisposable
{
    private const string Col = ReaderwareDbExportService.ColumnDelimiter;
    private const string Row = ReaderwareDbExportService.RowDelimiter;
    private const string Null = ReaderwareDbExportService.NullToken;

    private readonly List<string> _tempDirs = [];

    public void Dispose()
    {
        foreach (var dir in _tempDirs)
            if (Directory.Exists(dir))
                Directory.Delete(dir, recursive: true);
        GC.SuppressFinalize(this);
    }

    private string CreateTempDir()
    {
        var dir = Path.Combine(Path.GetTempPath(), $"rwexport_test_{Guid.NewGuid():N}");
        Directory.CreateDirectory(dir);
        _tempDirs.Add(dir);
        return dir;
    }

    private const string SampleScript =
        "SET DATABASE COLLATION \"Latin1_General\"\n" +
        "CREATE CACHED TABLE READERWARE(ROWKEY BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY," +
        "TITLE VARCHAR_IGNORECASE(255) NOT NULL)\n" +
        "CREATE CACHED TABLE FORMAT_LIST(ROWKEY BIGINT NOT NULL PRIMARY KEY,LISTITEM VARCHAR_IGNORECASE(32) NOT NULL)\n" +
        "CREATE MEMORY TABLE PREFERENCES(PREFS_KEY VARCHAR(128) NOT NULL PRIMARY KEY,PREFS_VALUE VARCHAR(4096))\n";

    [Fact]
    public void ParsesTableNamesAcrossTableKinds()
    {
        var names = ReaderwareDbExportService.ParseTableNames(SampleScript);
        Assert.Contains("READERWARE", names);
        Assert.Contains("FORMAT_LIST", names);
        Assert.Contains("PREFERENCES", names);
        Assert.DoesNotContain("CONTRIBUTOR", names);
    }

    [Fact]
    public void BuildsExportScriptWithSentinelsAndPerTableExport()
    {
        var script = ReaderwareDbExportService.BuildExportScript(
            new[] { "READERWARE", "FORMAT_LIST" }, @"C:\tmp\dsv");

        Assert.Contains($"* *DSV_COL_DELIM = {Col}", script);
        Assert.Contains($"* *DSV_ROW_DELIM = {Row}", script);
        Assert.Contains($"* *NULL_REP_TOKEN = {Null}", script);
        // Forward-slashed absolute target file per table, then the eXport command.
        Assert.Contains("* *DSV_TARGET_FILE = C:/tmp/dsv/READERWARE.dsv", script);
        Assert.Contains("\\x READERWARE", script);
        Assert.Contains("* *DSV_TARGET_FILE = C:/tmp/dsv/FORMAT_LIST.dsv", script);
        Assert.Contains("\\x FORMAT_LIST", script);
        Assert.EndsWith("\\q\n", script);
    }

    [Fact]
    public void ConvertWritesBomFreeUtf16Be()
    {
        var dir = CreateTempDir();
        var dest = Path.Combine(dir, "FORMAT_LIST");
        var dsv = $"ROWKEY{Col}LISTITEM{Row}1{Col}Hardcover{Row}2{Col}Paperback{Row}";

        ReaderwareDbExportService.ConvertDsvToBackupFile(dsv, dest);

        var bytes = File.ReadAllBytes(dest);
        Assert.False(bytes.Length >= 2 && bytes[0] == 0xFE && bytes[1] == 0xFF); // no BOM
        Assert.Equal(0x00, bytes[0]);
        Assert.Equal((byte)'R', bytes[1]);

        var text = new UnicodeEncoding(bigEndian: true, byteOrderMark: false).GetString(bytes);
        Assert.StartsWith("ROWKEY,LISTITEM\r\n", text);
    }

    [Fact]
    public async Task ConvertedDsvIsReadableByReaderwareBackupParser()
    {
        var folder = CreateTempDir();

        // Header carried by the DSV. Row 2's title contains a comma and an embedded newline —
        // proving DSV row boundaries survive content that would break naive CSV.
        var dsv =
            $"ROWKEY{Col}TITLE{Col}SIGNED{Row}" +
            $"1{Col}Plain Title{Col}-1{Row}" +
            $"2{Col}Comma, and\nnewline{Col}-1{Row}" +
            $"3{Col}{Null}{Col}-1{Row}";
        ReaderwareDbExportService.ConvertDsvToBackupFile(dsv, Path.Combine(folder, "READERWARE"));

        ReaderwareDbExportService.ConvertDsvToBackupFile($"ROWKEY{Col}EV{Row}", Path.Combine(folder, "DBCATALOG40"));

        var parser = new ReaderwareBackupParser();
        var result = await parser.ParseAsync(folder, TestContext.Current.CancellationToken);

        Assert.Equal(3, result.Books.Count);
        Assert.Equal("Plain Title", result.Books[0].Title);
        Assert.Equal("Comma, and\nnewline", result.Books[1].Title);
        // Null token became an empty title.
        Assert.Equal(string.Empty, result.Books[2].Title);
        Assert.DoesNotContain(result.Warnings, w => w.Contains("DBCATALOG40"));
    }

    [Fact]
    public async Task HeaderOnlyDsvParsesToZeroRows()
    {
        var folder = CreateTempDir();
        ReaderwareDbExportService.ConvertDsvToBackupFile($"ROWKEY{Col}TITLE{Row}", Path.Combine(folder, "READERWARE"));

        var parser = new ReaderwareBackupParser();
        var result = await parser.ParseAsync(folder, TestContext.Current.CancellationToken);

        Assert.Empty(result.Books);
    }

    [Fact]
    public void ConvertEmitsHexImageDataUnchanged()
    {
        var dir = CreateTempDir();
        var dest = Path.Combine(dir, "FULL_IMAGES");
        var dsv = $"ROW_ID{Col}IMAGE_INDEX{Col}IMAGE_DATA{Row}1{Col}0{Col}ffd8ffe000104a464946{Row}";

        ReaderwareDbExportService.ConvertDsvToBackupFile(dsv, dest);

        var text = new UnicodeEncoding(bigEndian: true, byteOrderMark: false).GetString(File.ReadAllBytes(dest));
        Assert.Contains("ffd8ffe000104a464946", text);
    }

    [Fact]
    public async Task ReportsToolPathInvalidWhenRuntimeMissing()
    {
        var dbDir = CreateTempDir();
        await File.WriteAllTextAsync(Path.Combine(dbDir, "MyBooksRW.rw4.properties"), "modified=no",
            TestContext.Current.CancellationToken);
        await File.WriteAllTextAsync(Path.Combine(dbDir, "MyBooksRW.rw4.script"), SampleScript,
            TestContext.Current.CancellationToken);

        var service = new ReaderwareDbExportService();
        var result = await service.ExportAsync(dbDir, CreateTempDir(), CreateTempDir() /* empty: no java/jar */,
            log: null, TestContext.Current.CancellationToken);

        Assert.Equal(ReaderwareExportFailure.ToolPathInvalid, result.Failure);
        Assert.False(result.Success);
    }

    [Fact]
    public async Task ReportsDatabaseInvalidWhenNoScriptPresent()
    {
        var toolDir = CreateTempDir();
        Directory.CreateDirectory(Path.Combine(toolDir, "jre", "bin"));
        Directory.CreateDirectory(Path.Combine(toolDir, "lib"));
        await File.WriteAllTextAsync(
            Path.Combine(toolDir, "jre", "bin", ReaderwareDbExportService.JavaExecutableName), "",
            TestContext.Current.CancellationToken);
        await File.WriteAllTextAsync(Path.Combine(toolDir, "lib", "hsqldb.jar"), "",
            TestContext.Current.CancellationToken);

        var service = new ReaderwareDbExportService();
        var result = await service.ExportAsync(CreateTempDir() /* empty db dir */, CreateTempDir(), toolDir,
            log: null, TestContext.Current.CancellationToken);

        Assert.Equal(ReaderwareExportFailure.DatabaseInvalid, result.Failure);
    }
}
