-- V001_CreateSchema.sql (PostgreSQL)
-- Provider-specific create-from-scratch script for the PostgreSQL backend. Mirrors the SQLite schema
-- with native types: boolean for bools, "timestamp without time zone" for dates, bytea for images,
-- identity columns for keys, and a generated tsvector column + GIN index in place of SQLite FTS5.
-- Identifiers are quoted to preserve the PascalCase names the shared EF model maps to.

-- ============================================================
-- Lookup tables (no foreign keys — create first)
-- ============================================================

CREATE TABLE "Collection" (
    "CollectionId"  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE,
    "SortOrder"     integer NOT NULL DEFAULT 0
);

CREATE TABLE "Person" (
    "PersonId"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DisplayName"   text    NOT NULL,
    "SortName"      text    NOT NULL,
    "Bio"           text    NULL,
    "BirthDate"     text    NULL,
    "BirthPlace"    text    NULL,
    "DeathDate"     text    NULL,
    "DeathPlace"    text    NULL,
    "Website"       text    NULL
);

CREATE TABLE "ContributorRole" (
    "ContributorRoleId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code"              text    NOT NULL UNIQUE,
    "DisplayName"       text    NOT NULL,
    "ResourceKey"       text    NULL
);

CREATE TABLE "Publisher" (
    "PublisherId"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE
);

CREATE TABLE "Series" (
    "SeriesId"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE
);

CREATE TABLE "Category" (
    "CategoryId"    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL,
    "SortOrder"     integer NOT NULL DEFAULT 0
);

CREATE TABLE "Condition" (
    "ConditionId"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE,
    "ResourceKey"   text    NULL
);

CREATE TABLE "Edition" (
    "EditionId"     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE,
    "ResourceKey"   text    NULL
);

CREATE TABLE "Format" (
    "FormatId"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE,
    "ResourceKey"   text    NULL
);

CREATE TABLE "Language" (
    "LanguageId"    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE,
    "ResourceKey"   text    NULL
);

CREATE TABLE "Location" (
    "LocationId"    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE
);

CREATE TABLE "Owner" (
    "OwnerId"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE
);

CREATE TABLE "PurchasePlace" (
    "PurchasePlaceId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"            text    NOT NULL UNIQUE
);

-- NumericValue allows ratings to be ordered numerically (e.g. 1.0-5.0) independent of display name.
CREATE TABLE "Rating" (
    "RatingId"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text             NOT NULL UNIQUE,
    "NumericValue"  double precision NULL,
    "ResourceKey"   text             NULL
);

CREATE TABLE "ReadingLevel" (
    "ReadingLevelId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"           text   NOT NULL UNIQUE,
    "ResourceKey"    text   NULL
);

CREATE TABLE "Source" (
    "SourceId"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE
);

CREATE TABLE "Status" (
    "StatusId"      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE,
    "ResourceKey"   text    NULL
);

-- Fixed enum-like lookups with explicit ids: plain integer keys (never inserted by the app).
CREATE TABLE "BorrowerStatus" (
    "BorrowerStatusId" integer PRIMARY KEY,
    "StatusName"       text    NOT NULL,
    "ResourceKey"      text    NULL
);

CREATE TABLE "BookImageType" (
    "BookImageTypeId" integer PRIMARY KEY,
    "TypeName"        text    NOT NULL,
    "ResourceKey"     text    NULL
);

-- ============================================================
-- Cross-reference tables that depend only on lookup tables
-- ============================================================

CREATE TABLE "CategoryCollection" (
    "CategoryId"    integer NOT NULL REFERENCES "Category"("CategoryId") ON DELETE CASCADE,
    "CollectionId"  integer NOT NULL REFERENCES "Collection"("CollectionId") ON DELETE CASCADE,
    PRIMARY KEY ("CategoryId", "CollectionId")
);

-- ============================================================
-- Core entity tables
-- ============================================================

CREATE TABLE "Book" (
    "BookId"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CollectionId"      integer REFERENCES "Collection"("CollectionId"),
    "Title"             text    NOT NULL,
    "Subtitle"          text    NULL,
    "PublisherId"       integer REFERENCES "Publisher"("PublisherId"),
    "PubPlace"          text    NULL,
    "PubDate"           text    NULL,
    "CopyrightDate"     text    NULL,
    "FormatId"          integer REFERENCES "Format"("FormatId"),
    "EditionId"         integer REFERENCES "Edition"("EditionId"),
    "Pages"             integer NULL,
    "Copies"            integer NOT NULL DEFAULT 1,
    "Isbn"              text    NULL,
    "LanguageId"        integer REFERENCES "Language"("LanguageId"),
    "SeriesId"          integer REFERENCES "Series"("SeriesId"),
    "SeriesNumber"      text    NULL,
    "ReadCount"         integer NOT NULL DEFAULT 0,
    "RatingId"          integer REFERENCES "Rating"("RatingId"),
    "ConditionId"       integer REFERENCES "Condition"("ConditionId"),
    "LocationId"        integer REFERENCES "Location"("LocationId"),
    "OwnerId"           integer REFERENCES "Owner"("OwnerId"),
    "StatusId"          integer REFERENCES "Status"("StatusId"),
    "Signed"            boolean NOT NULL DEFAULT false,
    "OutOfPrint"        boolean NOT NULL DEFAULT false,
    "Favorite"          boolean NOT NULL DEFAULT false,
    "Keywords"          text    NULL,
    "Comments"          text    NULL,
    "BookInfo"          text    NULL,
    "PurchasePrice"     numeric NULL,
    "PurchasePlaceId"   integer REFERENCES "PurchasePlace"("PurchasePlaceId"),
    "ListPrice"         numeric NULL,
    "SourceId"          integer REFERENCES "Source"("SourceId"),
    "ExternalId"        text    NULL,
    "MediaLink"         text    NULL,
    "Display"           boolean NOT NULL DEFAULT true,
    "ReadingLevelId"    integer REFERENCES "ReadingLevel"("ReadingLevelId"),
    "Added"             timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "Updated"           timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "PurchaseCurrency"  text    NULL,
    "ListPriceCurrency" text    NULL,
    "AltTitle"          text    NULL,
    "AmazonAsin"        text    NULL,
    "PurchaseDate"      timestamp without time zone NULL,
    "DateLastRead"      timestamp without time zone NULL,
    "Issn"              text    NULL,
    "Lccn"              text    NULL,
    "DeweyDecimal"      text    NULL,
    "CallNumber"        text    NULL,
    "Dimensions"        text    NULL,
    "Weight"            numeric NULL,
    "ItemValue"         numeric NULL,
    "ValuationDate"     timestamp without time zone NULL,
    "AmazonNewValue"         numeric NULL,
    "AmazonUsedValue"        numeric NULL,
    "AmazonCollectibleValue" numeric NULL,
    "AmazonNewCount"         integer NULL,
    "AmazonUsedCount"        integer NULL,
    "AmazonCollectibleCount" integer NULL,
    "SalesRank"              integer NULL,
    "LexileLevel"           integer NULL,
    -- Full-text search vector (replaces SQLite FTS5). Auto-maintained from the indexed columns.
    "SearchVector" tsvector GENERATED ALWAYS AS (
        to_tsvector('simple',
            coalesce("Title", '')      || ' ' ||
            coalesce("Subtitle", '')   || ' ' ||
            coalesce("Keywords", '')   || ' ' ||
            coalesce("Comments", '')   || ' ' ||
            coalesce("BookInfo", '')   || ' ' ||
            coalesce("ExternalId", ''))) STORED
);

CREATE TABLE "BookContributor" (
    "BookContributorId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BookId"            integer NOT NULL REFERENCES "Book"("BookId") ON DELETE CASCADE,
    "PersonId"          integer NOT NULL REFERENCES "Person"("PersonId"),
    "ContributorRoleId" integer NOT NULL REFERENCES "ContributorRole"("ContributorRoleId"),
    "SortOrder"         integer NOT NULL DEFAULT 0
);

CREATE TABLE "BookCategory" (
    "BookId"      integer NOT NULL REFERENCES "Book"("BookId") ON DELETE CASCADE,
    "CategoryId"  integer NOT NULL REFERENCES "Category"("CategoryId"),
    PRIMARY KEY ("BookId", "CategoryId")
);

CREATE TABLE "Settings" (
    "Key"     text PRIMARY KEY,
    "Value"   text NULL
);

CREATE TABLE "SavedSearch" (
    "SavedSearchId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name"          text    NOT NULL UNIQUE,
    "QueryJson"     text    NOT NULL,
    "CreatedAt"     timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE TABLE "BatchQueueItem" (
    "BatchQueueItemId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Isbn"             text    NOT NULL,
    "BookId"           integer,
    "Status"           text    NOT NULL DEFAULT 'Pending',
    "ResultJson"       text,
    "CreatedAt"        timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "UpdatedAt"        timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE TABLE "BookImage" (
    "BookImageId"     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BookId"          integer NOT NULL REFERENCES "Book"("BookId") ON DELETE CASCADE,
    "ImageData"       bytea   NOT NULL,
    "MimeType"        text    NOT NULL DEFAULT 'image/jpeg',
    "IsPrimary"       boolean NOT NULL DEFAULT false,
    "DisplayOrder"    integer NOT NULL DEFAULT 0,
    "Added"           timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "BookImageTypeId" integer NOT NULL DEFAULT 0 REFERENCES "BookImageType"("BookImageTypeId")
);

CREATE TABLE "BookVolume" (
    "BookVolumeId"  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BookId"        integer NOT NULL REFERENCES "Book"("BookId") ON DELETE CASCADE,
    "VolumeNumber"  integer NOT NULL
);

CREATE TABLE "BookChapter" (
    "BookChapterId"  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BookVolumeId"   integer NOT NULL REFERENCES "BookVolume"("BookVolumeId") ON DELETE CASCADE,
    "ChapterNumber"  integer NOT NULL
);

CREATE TABLE "Borrower" (
    "BorrowerId"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StatusId"            integer NOT NULL DEFAULT 0 REFERENCES "BorrowerStatus"("BorrowerStatusId"),
    "FirstName"           text NULL,
    "LastName"            text NULL,
    "BorrowerExternalId"  text NULL,
    "Organization"        text NULL,
    "Address1"            text NULL,
    "Address2"            text NULL,
    "City"                text NULL,
    "State"               text NULL,
    "PostalCode"          text NULL,
    "Country"             text NULL,
    "Phone1"              text NULL,
    "Phone2"              text NULL,
    "Email"               text NULL,
    "Fax"                 text NULL
);

-- Loan records are historical: deleting a Book or Borrower with associated loans is blocked.
CREATE TABLE "Loan" (
    "LoanId"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BookId"          integer NOT NULL REFERENCES "Book"("BookId") ON DELETE RESTRICT,
    "BorrowerId"      integer NOT NULL REFERENCES "Borrower"("BorrowerId") ON DELETE RESTRICT,
    "LoanedDate"      timestamp without time zone NULL,
    "DueDate"         timestamp without time zone NULL,
    "ReturnedDate"    timestamp without time zone NULL,
    "LoanExternalId"  text NULL
);

-- Multi-client detection: a lightweight heartbeat/session table (enforced only for remote backends).
CREATE TABLE "ClientSession" (
    "SessionId"   text PRIMARY KEY,
    "Hostname"    text NOT NULL,
    "UserName"    text NOT NULL,
    "AppVersion"  text NOT NULL,
    "StartedAt"   timestamp without time zone NOT NULL,
    "LastSeenAt"  timestamp without time zone NOT NULL
);

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX "IX_Book_CollectionId"        ON "Book" ("CollectionId");
CREATE INDEX "IX_Book_PublisherId"         ON "Book" ("PublisherId");
CREATE INDEX "IX_Book_SeriesId"            ON "Book" ("SeriesId");
CREATE INDEX "IX_Book_Isbn"                ON "Book" ("Isbn");
CREATE INDEX "IX_Book_StatusId"            ON "Book" ("StatusId");
CREATE INDEX "IX_Book_FormatId"            ON "Book" ("FormatId");
CREATE INDEX "IX_Book_LanguageId"          ON "Book" ("LanguageId");
CREATE INDEX "IX_Book_LocationId"          ON "Book" ("LocationId");
CREATE INDEX "IX_Book_OwnerId"             ON "Book" ("OwnerId");
CREATE INDEX "IX_Book_RatingId"            ON "Book" ("RatingId");
CREATE INDEX "IX_BookContributor_BookId"   ON "BookContributor" ("BookId");
CREATE INDEX "IX_BookContributor_PersonId" ON "BookContributor" ("PersonId");
CREATE INDEX "IX_BookCategory_CategoryId"  ON "BookCategory" ("CategoryId");
CREATE INDEX "IX_BookImage_BookId"         ON "BookImage" ("BookId");
CREATE INDEX "IX_BookVolume_BookId"        ON "BookVolume" ("BookId");
CREATE INDEX "IX_BookChapter_BookVolumeId" ON "BookChapter" ("BookVolumeId");
CREATE INDEX "IX_BatchQueueItem_Status"    ON "BatchQueueItem" ("Status");
CREATE INDEX "IX_Book_Collection_Status"   ON "Book" ("CollectionId", "StatusId");
CREATE INDEX "IX_Book_Collection_Format"   ON "Book" ("CollectionId", "FormatId");

-- Partial unique index: allows NULL ISBNs and empty strings (books without ISBNs).
CREATE UNIQUE INDEX "UX_Book_Isbn" ON "Book" ("Isbn") WHERE "Isbn" IS NOT NULL AND "Isbn" <> '';

-- Full-text GIN index over the generated search vector. Plain CREATE INDEX (no CONCURRENTLY) so it
-- runs inside DbUp's transaction.
CREATE INDEX "IX_Book_SearchVector" ON "Book" USING GIN ("SearchVector");

-- ============================================================
-- Seed data
-- ============================================================

INSERT INTO "Collection" ("Name", "SortOrder") VALUES ('Comics', 1) ON CONFLICT DO NOTHING;
INSERT INTO "Collection" ("Name", "SortOrder") VALUES ('Fiction', 2) ON CONFLICT DO NOTHING;
INSERT INTO "Collection" ("Name", "SortOrder") VALUES ('Non-Fiction', 3) ON CONFLICT DO NOTHING;

INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Author', 'Author', 'ContributorRole_Author') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Editor', 'Editor', 'ContributorRole_Editor') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Translator', 'Translator', 'ContributorRole_Translator') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Foreword', 'Foreword', 'ContributorRole_Foreword') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Introduction', 'Introduction', 'ContributorRole_Introduction') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Illustrator', 'Illustrator', 'ContributorRole_Illustrator') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Writer', 'Writer', 'ContributorRole_Writer') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Penciller', 'Penciller', 'ContributorRole_Penciller') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Inker', 'Inker', 'ContributorRole_Inker') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Colorist', 'Colorist', 'ContributorRole_Colorist') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Letterer', 'Letterer', 'ContributorRole_Letterer') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('CoverArtist', 'Cover Artist', 'ContributorRole_CoverArtist') ON CONFLICT DO NOTHING;
INSERT INTO "ContributorRole" ("Code", "DisplayName", "ResourceKey") VALUES ('Designer', 'Designer', 'ContributorRole_Designer') ON CONFLICT DO NOTHING;

INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Adventure', 1) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Biography', 2) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Children', 3) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Classic', 4) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Crime', 5) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Fantasy', 6) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('History', 7) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Horror', 8) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Humor', 9) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Mystery', 10) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Poetry', 11) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Reference', 12) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Romance', 13) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Science', 14) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Science Fiction', 15) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Self-Help', 16) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Superhero', 17) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Thriller', 18) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Travel', 19) ON CONFLICT DO NOTHING;
INSERT INTO "Category" ("Name", "SortOrder") VALUES ('Young Adult', 20) ON CONFLICT DO NOTHING;

INSERT INTO "CategoryCollection" ("CategoryId", "CollectionId")
SELECT c."CategoryId", col."CollectionId"
FROM "Category" c
CROSS JOIN "Collection" col
ON CONFLICT DO NOTHING;

INSERT INTO "Format" ("Name", "ResourceKey") VALUES ('Hardcover', 'Format_Hardcover') ON CONFLICT DO NOTHING;
INSERT INTO "Format" ("Name", "ResourceKey") VALUES ('Paperback', 'Format_Paperback') ON CONFLICT DO NOTHING;
INSERT INTO "Format" ("Name", "ResourceKey") VALUES ('Trade Paperback', 'Format_TradePaperback') ON CONFLICT DO NOTHING;
INSERT INTO "Format" ("Name", "ResourceKey") VALUES ('Mass Market Paperback', 'Format_MassMarketPaperback') ON CONFLICT DO NOTHING;
INSERT INTO "Format" ("Name", "ResourceKey") VALUES ('E-book', 'Format_Ebook') ON CONFLICT DO NOTHING;
INSERT INTO "Format" ("Name", "ResourceKey") VALUES ('Audiobook', 'Format_Audiobook') ON CONFLICT DO NOTHING;
INSERT INTO "Format" ("Name", "ResourceKey") VALUES ('Graphic Novel', 'Format_GraphicNovel') ON CONFLICT DO NOTHING;
INSERT INTO "Format" ("Name", "ResourceKey") VALUES ('Comic', 'Format_Comic') ON CONFLICT DO NOTHING;
INSERT INTO "Format" ("Name", "ResourceKey") VALUES ('Magazine', 'Format_Magazine') ON CONFLICT DO NOTHING;

INSERT INTO "Condition" ("Name", "ResourceKey") VALUES ('New', 'Condition_New') ON CONFLICT DO NOTHING;
INSERT INTO "Condition" ("Name", "ResourceKey") VALUES ('Like New', 'Condition_LikeNew') ON CONFLICT DO NOTHING;
INSERT INTO "Condition" ("Name", "ResourceKey") VALUES ('Very Good', 'Condition_VeryGood') ON CONFLICT DO NOTHING;
INSERT INTO "Condition" ("Name", "ResourceKey") VALUES ('Good', 'Condition_Good') ON CONFLICT DO NOTHING;
INSERT INTO "Condition" ("Name", "ResourceKey") VALUES ('Fair', 'Condition_Fair') ON CONFLICT DO NOTHING;
INSERT INTO "Condition" ("Name", "ResourceKey") VALUES ('Poor', 'Condition_Poor') ON CONFLICT DO NOTHING;

INSERT INTO "Edition" ("Name", "ResourceKey") VALUES ('1st Edition', 'Edition_1stEdition') ON CONFLICT DO NOTHING;
INSERT INTO "Edition" ("Name", "ResourceKey") VALUES ('2nd Edition', 'Edition_2ndEdition') ON CONFLICT DO NOTHING;
INSERT INTO "Edition" ("Name", "ResourceKey") VALUES ('3rd Edition', 'Edition_3rdEdition') ON CONFLICT DO NOTHING;
INSERT INTO "Edition" ("Name", "ResourceKey") VALUES ('Revised Edition', 'Edition_RevisedEdition') ON CONFLICT DO NOTHING;
INSERT INTO "Edition" ("Name", "ResourceKey") VALUES ('Collector''s Edition', 'Edition_CollectorsEdition') ON CONFLICT DO NOTHING;
INSERT INTO "Edition" ("Name", "ResourceKey") VALUES ('Limited Edition', 'Edition_LimitedEdition') ON CONFLICT DO NOTHING;
INSERT INTO "Edition" ("Name", "ResourceKey") VALUES ('Signed Edition', 'Edition_SignedEdition') ON CONFLICT DO NOTHING;

INSERT INTO "Language" ("Name", "ResourceKey") VALUES ('English', 'Language_English') ON CONFLICT DO NOTHING;
INSERT INTO "Language" ("Name", "ResourceKey") VALUES ('Swedish', 'Language_Swedish') ON CONFLICT DO NOTHING;
INSERT INTO "Language" ("Name", "ResourceKey") VALUES ('French', 'Language_French') ON CONFLICT DO NOTHING;
INSERT INTO "Language" ("Name", "ResourceKey") VALUES ('German', 'Language_German') ON CONFLICT DO NOTHING;
INSERT INTO "Language" ("Name", "ResourceKey") VALUES ('Spanish', 'Language_Spanish') ON CONFLICT DO NOTHING;
INSERT INTO "Language" ("Name", "ResourceKey") VALUES ('Italian', 'Language_Italian') ON CONFLICT DO NOTHING;
INSERT INTO "Language" ("Name", "ResourceKey") VALUES ('Japanese', 'Language_Japanese') ON CONFLICT DO NOTHING;
INSERT INTO "Language" ("Name", "ResourceKey") VALUES ('Norwegian', 'Language_Norwegian') ON CONFLICT DO NOTHING;
INSERT INTO "Language" ("Name", "ResourceKey") VALUES ('Danish', 'Language_Danish') ON CONFLICT DO NOTHING;
INSERT INTO "Language" ("Name", "ResourceKey") VALUES ('Finnish', 'Language_Finnish') ON CONFLICT DO NOTHING;

INSERT INTO "Rating" ("Name", "NumericValue", "ResourceKey") VALUES ('1 Star', 1.0, 'Rating_1Star') ON CONFLICT DO NOTHING;
INSERT INTO "Rating" ("Name", "NumericValue", "ResourceKey") VALUES ('2 Stars', 2.0, 'Rating_2Stars') ON CONFLICT DO NOTHING;
INSERT INTO "Rating" ("Name", "NumericValue", "ResourceKey") VALUES ('3 Stars', 3.0, 'Rating_3Stars') ON CONFLICT DO NOTHING;
INSERT INTO "Rating" ("Name", "NumericValue", "ResourceKey") VALUES ('4 Stars', 4.0, 'Rating_4Stars') ON CONFLICT DO NOTHING;
INSERT INTO "Rating" ("Name", "NumericValue", "ResourceKey") VALUES ('5 Stars', 5.0, 'Rating_5Stars') ON CONFLICT DO NOTHING;

INSERT INTO "Status" ("Name", "ResourceKey") VALUES ('Owned', 'Status_Owned') ON CONFLICT DO NOTHING;
INSERT INTO "Status" ("Name", "ResourceKey") VALUES ('Wishlist', 'Status_Wishlist') ON CONFLICT DO NOTHING;
INSERT INTO "Status" ("Name", "ResourceKey") VALUES ('On Order', 'Status_OnOrder') ON CONFLICT DO NOTHING;
INSERT INTO "Status" ("Name", "ResourceKey") VALUES ('Borrowed', 'Status_Borrowed') ON CONFLICT DO NOTHING;
INSERT INTO "Status" ("Name", "ResourceKey") VALUES ('Sold', 'Status_Sold') ON CONFLICT DO NOTHING;
INSERT INTO "Status" ("Name", "ResourceKey") VALUES ('Given Away', 'Status_GivenAway') ON CONFLICT DO NOTHING;

INSERT INTO "ReadingLevel" ("Name", "ResourceKey") VALUES ('Easy Reader', 'ReadingLevel_EasyReader') ON CONFLICT DO NOTHING;
INSERT INTO "ReadingLevel" ("Name", "ResourceKey") VALUES ('Middle Grade', 'ReadingLevel_MiddleGrade') ON CONFLICT DO NOTHING;
INSERT INTO "ReadingLevel" ("Name", "ResourceKey") VALUES ('Young Adult', 'ReadingLevel_YoungAdult') ON CONFLICT DO NOTHING;
INSERT INTO "ReadingLevel" ("Name", "ResourceKey") VALUES ('Adult', 'ReadingLevel_Adult') ON CONFLICT DO NOTHING;

INSERT INTO "Location" ("Name") VALUES ('Default') ON CONFLICT DO NOTHING;
INSERT INTO "Owner" ("Name") VALUES ('Me') ON CONFLICT DO NOTHING;
INSERT INTO "Publisher" ("Name") VALUES ('Unknown') ON CONFLICT DO NOTHING;
INSERT INTO "PurchasePlace" ("Name") VALUES ('Unknown') ON CONFLICT DO NOTHING;
INSERT INTO "Series" ("Name") VALUES ('Standalone') ON CONFLICT DO NOTHING;
INSERT INTO "Source" ("Name") VALUES ('Manual Entry') ON CONFLICT DO NOTHING;

INSERT INTO "Settings" ("Key", "Value") VALUES ('PrimaryDisplayRole', 'Author') ON CONFLICT DO NOTHING;

INSERT INTO "BookImageType" ("BookImageTypeId", "TypeName", "ResourceKey") VALUES (0, 'Cover', 'BookImageType_Cover') ON CONFLICT DO NOTHING;
INSERT INTO "BookImageType" ("BookImageTypeId", "TypeName", "ResourceKey") VALUES (1, 'Thumbnail', 'BookImageType_Thumbnail') ON CONFLICT DO NOTHING;
INSERT INTO "BookImageType" ("BookImageTypeId", "TypeName", "ResourceKey") VALUES (2, 'BackCover', 'BookImageType_BackCover') ON CONFLICT DO NOTHING;
INSERT INTO "BookImageType" ("BookImageTypeId", "TypeName", "ResourceKey") VALUES (3, 'Spine', 'BookImageType_Spine') ON CONFLICT DO NOTHING;
INSERT INTO "BookImageType" ("BookImageTypeId", "TypeName", "ResourceKey") VALUES (4, 'DustJacket', 'BookImageType_DustJacket') ON CONFLICT DO NOTHING;

INSERT INTO "BorrowerStatus" ("BorrowerStatusId", "StatusName", "ResourceKey") VALUES (0, 'Active', 'BorrowerStatus_Active') ON CONFLICT DO NOTHING;
INSERT INTO "BorrowerStatus" ("BorrowerStatusId", "StatusName", "ResourceKey") VALUES (1, 'Inactive', 'BorrowerStatus_Inactive') ON CONFLICT DO NOTHING;
