-- V002_AddBatchReviewAndCleanupIgnore.sql (PostgreSQL)
-- Appended after V001 (which stays untouched; PostgreSQL shipped later, so ClientSession is
-- already in its V001 and this is its first delta script). BatchQueueItem gains a per-item
-- force-review flag (a guided single-book add must always land in review, even when all sources
-- agree) and a failure code (a localizable reason instead of a bare failed status). EF supplies
-- FailureCode values, so it carries no DEFAULT; ForceReview defaults to false for existing rows.
--
-- PersonCleanupIgnore persists dismissed person-name cleanup proposals. The unique key is the
-- proposal's content, not just the person: a scan skips a proposal only while it would re-derive
-- exactly the same suggestion, so changed person data surfaces a fresh proposal despite an old
-- ignore. Rows die with their person (split-apply deletes the source person).

ALTER TABLE "BatchQueueItem"
    ADD COLUMN "ForceReview" boolean NOT NULL DEFAULT false,
    ADD COLUMN "FailureCode" text;

CREATE TABLE "PersonCleanupIgnore" (
    "PersonCleanupIgnoreId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PersonId"              integer NOT NULL REFERENCES "Person"("PersonId") ON DELETE CASCADE,
    "Kind"                  text    NOT NULL,
    "ProposedContent"       text    NOT NULL,
    "CreatedAt"             timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT "UX_PersonCleanupIgnore_Fingerprint" UNIQUE ("PersonId", "Kind", "ProposedContent")
);
